module.exports = {
  darkMode: "class",
  content: ["./*.html", "./*.md"],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#1b251d",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#410005",
        "surface-container-low": "#101712",
        "secondary-container": "#404758",
        "on-tertiary-fixed-variant": "#920117",
        "on-background": "#f1f5f1",
        "on-primary": "#00391c",
        tertiary: "#ffb3af",
        "inverse-primary": "#006d3b",
        "tertiary-fixed": "#ffdad7",
        "on-surface-variant": "#a4b2a7",
        outline: "#8faf9a",
        "on-secondary-fixed-variant": "#404758",
        "on-secondary": "#293040",
        "surface-container-highest": "#1b251d",
        "surface-container-high": "#1b251d",
        "on-secondary-fixed": "#141b2b",
        background: "#080D0A",
        "primary-fixed-dim": "#42e189",
        "outline-variant": "#3c4a3f",
        "surface-tint": "#00c26e",
        "on-tertiary": "#68000d",
        "on-secondary-container": "#aeb5c9",
        "surface-container": "#151d17",
        "tertiary-container": "#ff8580",
        "surface-variant": "#1b251d",
        "on-primary-fixed-variant": "#00522b",
        "secondary-fixed": "#dce2f7",
        "surface-container-lowest": "#050705",
        "inverse-surface": "#dce5db",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#2a322c",
        "surface-dim": "#080D0A",
        "on-surface": "#f1f5f1",
        "secondary-fixed-dim": "#c0c6db",
        "tertiary-fixed-dim": "#ffb3af",
        "on-primary-container": "#004825",
        "primary-container": "#00c26e",
        "on-error": "#690005",
        primary: "#00c26e",
        "primary-fixed": "#65fea3",
        error: "#ffb4ab",
        surface: "#151d17",
        secondary: "#c0c6db",
        "on-tertiary-container": "#820013",
        "on-primary-fixed": "#00210e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "max-width": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        base: "8px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
